export const personList = [
  {
    id: 1,
    firstName: "Cristobal",
    lastName: "Rannells",
    userPhoto: "http://dummyimage.com/160x100.png/5fa2dd/ffffff",
    userMail: "crannells0@printfriendly.com",
    userGender: "Non-binary",
  },
  {
    id: 2,
    firstName: "Brooks",
    lastName: "Duggary",
    userPhoto: "http://dummyimage.com/239x100.png/ff4444/ffffff",
    userMail: "bduggary1@hubpages.com",
    userGender: "Male",
  },
  {
    id: 3,
    firstName: "Isiahi",
    lastName: "Hartland",
    userPhoto: "http://dummyimage.com/181x100.png/5fa2dd/ffffff",
    userMail: "ihartland2@yelp.com",
    userGender: "Bigender",
  },
  {
    id: 4,
    firstName: "Torrence",
    lastName: "Hughill",
    userPhoto: "http://dummyimage.com/205x100.png/dddddd/000000",
    userMail: "thughill3@fema.gov",
    userGender: "Genderqueer",
  },
  {
    id: 5,
    firstName: "Bradley",
    lastName: "Whear",
    userPhoto: "http://dummyimage.com/247x100.png/cc0000/ffffff",
    userMail: "bwhear4@sciencedaily.com",
    userGender: "Male",
  },
  {
    id: 6,
    firstName: "Clim",
    lastName: "Pinnell",
    userPhoto: "http://dummyimage.com/212x100.png/5fa2dd/ffffff",
    userMail: "cpinnell5@xrea.com",
    userGender: "Genderfluid",
  },
  {
    id: 7,
    firstName: "Eliot",
    lastName: "Haggett",
    userPhoto: "http://dummyimage.com/234x100.png/ff4444/ffffff",
    userMail: "ehaggett6@over-blog.com",
    userGender: "Male",
  },
  {
    id: 8,
    firstName: "Koral",
    lastName: "Furniss",
    userPhoto: "http://dummyimage.com/101x100.png/ff4444/ffffff",
    userMail: "kfurniss7@newyorker.com",
    userGender: "Female",
  },
  {
    id: 9,
    firstName: "Ian",
    lastName: "Cornu",
    userPhoto: "http://dummyimage.com/244x100.png/5fa2dd/ffffff",
    userMail: "icornu8@smugmug.com",
    userGender: "Male",
  },
  {
    id: 10,
    firstName: "Velma",
    lastName: "Geeraert",
    userPhoto: "http://dummyimage.com/189x100.png/ff4444/ffffff",
    userMail: "vgeeraert9@youku.com",
    userGender: "Female",
  },
  {
    id: 11,
    firstName: "Gardy",
    lastName: "Lodford",
    userPhoto: "http://dummyimage.com/142x100.png/dddddd/000000",
    userMail: "glodforda@nytimes.com",
    userGender: "Male",
  },
  {
    id: 12,
    firstName: "Dniren",
    lastName: "McCritichie",
    userPhoto: "http://dummyimage.com/107x100.png/ff4444/ffffff",
    userMail: "dmccritichieb@google.ru",
    userGender: "Female",
  },
  {
    id: 13,
    firstName: "Jake",
    lastName: "Brockelsby",
    userPhoto: "http://dummyimage.com/207x100.png/cc0000/ffffff",
    userMail: "jbrockelsbyc@wordpress.org",
    userGender: "Male",
  },
  {
    id: 14,
    firstName: "Jed",
    lastName: "Neeves",
    userPhoto: "http://dummyimage.com/240x100.png/5fa2dd/ffffff",
    userMail: "jneevesd@si.edu",
    userGender: "Male",
  },
  {
    id: 15,
    firstName: "Daveen",
    lastName: "Bucklee",
    userPhoto: "http://dummyimage.com/186x100.png/ff4444/ffffff",
    userMail: "dbuckleee@shutterfly.com",
    userGender: "Female",
  },
];
